### ISSUE TITLE
Testing Existing Algorithms

### ISSUE THREAD

**Issue by Caposto** [stevensblueprint/aad-matching-service#4]
# Description

Find an existing algorithm written in Python and see how it performs against Brandon's output.

Find existing JavaScript implementations of the Gale-Shapley Matching Algorithm. Run a local example on a custom dataset to see which one aligns best with our project's needs. Can also explore algorithms written in different coding languages.

# Definition of Done
- [x] Report which libraries are viable or if we need to start completely from scratch
- [x] Generate a csv of Brandon's output and a csv of the other algo

**Story Points: 3**

**Comment by Banani456** [comment]
https://docs.google.com/document/d/16a-XPdqIR-1gBbTm00rEKDWdxtq9HS4llEXVauXhhp0/edit?usp=sharing

**Comment by Banani456** [comment]
Most likely need to start from scratch, some useful links are listed above of different algorithms that can allow us to create a matching algorithm.

**Comment by Banani456** [comment]
https://github.com/c0mput3r5c13nt15t/mint-vernetzt-hackathon-mapping-matching-algorithm/blob/main/main.py

https://github.com/janinepdevera/GetHelp

https://github.com/speters9/JobMatch
